image: node:22

stages:
  - test
  - build

variables:
  DATA_DIR: ./data-test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

test:
  stage: test
  script:
    - npm run test
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  needs:
    - test
